pull request after demo
iBaryo/gigya-cdp-sdk pull request #4
Opened 2020-12-27 08:30 UTC by yourgirlcodes

2021-01-01 20:07 UTC, iBaryo requested changes

2021-01-01 20:07 UTC, iBaryo commented on entities/Event/EventMapping.ts
> +    target?: SchemaId;
why?.. event mapping always require a target schema

2021-01-01 20:07 UTC, iBaryo commented on entities/common/mapping.ts
> +    srcField?: string;
lets drop this field as it's deprecated

2021-01-01 20:07 UTC, iBaryo commented on CDPEntitiesApi.ts
> +            applibrary: EntityApi<CDPEntityDef<Connector[]>>,
why? the type provided to `CDPEntityDev` represents the response of a single GET

2021-01-01 20:07 UTC, iBaryo commented on entities/Audience/AudienceCondition.ts
> +// const conditionExample: AudienceCondition = {
please uncomment this - if something's not compiling then it needs to be fixed.

2021-01-03 11:14 UTC, yourgirlcodes commented
relevant for CR

2021-01-06 17:12 UTC, closed without merging

2021-01-06 17:12 UTC, yourgirlcodes commented
irrelevant